"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
import { demoSlots,professionals,services,type Modality,type TimeSlot } from "@/lib/scheduling";
import { formatBrazilianPhone } from "@/lib/phone";

type Selection={modality?:Modality;serviceId?:string;professionalId?:string;slotId?:string};
type LiveSlot=TimeSlot&{live:true};
type Submission={status:"idle"|"sending"|"success"|"error";message?:string};
const steps=["Modalidade","Atendimento","Profissional","Horário","Identificação"];

export function SchedulingWizard(){
  const [selection,setSelection]=useState<Selection>({});
  const [liveSlots,setLiveSlots]=useState<LiveSlot[]>([]);
  const [mode,setMode]=useState<"checking"|"demo"|"live">("checking");
  const [identifying,setIdentifying]=useState(false);
  const [dayIndex,setDayIndex]=useState(0);
  const [submission,setSubmission]=useState<Submission>({status:"idle"});
  const activeStep=identifying?4:selection.professionalId?3:selection.serviceId?2:selection.modality?1:0;
  const availableServices=services.filter(item=>selection.modality&&item.modalities.includes(selection.modality));
  const availableProfessionals=professionals.filter(item=>selection.modality&&selection.serviceId&&item.modalities.includes(selection.modality)&&item.serviceIds.includes(selection.serviceId));

  useEffect(()=>{
    if(!selection.modality||!selection.serviceId||!selection.professionalId)return;
    const params=new URLSearchParams({modality:selection.modality,service:selection.serviceId,professional:selection.professionalId});
    fetch(`/api/availability?${params}`).then(async response=>{if(!response.ok)throw new Error();const payload=await response.json();
      const day=new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"2-digit",month:"short",timeZone:"America/Sao_Paulo"});
      const time=new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"America/Sao_Paulo"});
      setLiveSlots(payload.slots.map((slot:{id:string;starts_at:string;professional_slug:string;service_slug:string})=>({id:slot.id,professionalId:slot.professional_slug,modality:selection.modality!,serviceId:slot.service_slug,date:slot.starts_at,dayLabel:day.format(new Date(slot.starts_at)),time:time.format(new Date(slot.starts_at)),live:true})));
      setMode("live");
    }).catch(()=>{setLiveSlots([]);setMode("demo")});
  },[selection.modality,selection.serviceId,selection.professionalId]);

  const fallback=useMemo(()=>demoSlots.filter(slot=>slot.modality===selection.modality&&slot.serviceId===selection.serviceId&&(selection.professionalId==="first-available"||slot.professionalId===selection.professionalId)),[selection]);
  const slots:TimeSlot[]=mode==="live"?liveSlots:fallback;
  const days=useMemo(()=>{const groups=new Map<string,TimeSlot[]>();for(const slot of slots){const key=dateKey(slot.date);groups.set(key,[...(groups.get(key)??[]),slot])}return [...groups.entries()].map(([date,items])=>({date,label:items[0].dayLabel,items}))},[slots]);
  const visibleDays=days.slice(dayIndex,dayIndex+3);
  const selectedSlot=slots.find(slot=>slot.id===selection.slotId);
  const selectedService=services.find(item=>item.id===selection.serviceId);
  const selectedProfessional=professionals.find(item=>item.id===(selection.professionalId==="first-available"?selectedSlot?.professionalId:selection.professionalId));

  function choose(target:keyof Selection,value:string){setIdentifying(false);setSubmission({status:"idle"});if(target==="modality")setSelection({modality:value as Modality});if(target==="serviceId")setSelection(current=>({modality:current.modality,serviceId:value}));if(target==="professionalId"){setMode("checking");setDayIndex(0);setSelection(current=>({modality:current.modality,serviceId:current.serviceId,professionalId:value}))}if(target==="slotId")setSelection(current=>({...current,slotId:value}))}
  function goToStep(index:number){if(index>activeStep)return;if(index===0){setSelection({});setIdentifying(false)}if(index===1){setSelection({modality:selection.modality});setIdentifying(false)}if(index===2){setSelection({modality:selection.modality,serviceId:selection.serviceId});setIdentifying(false)}if(index===3){setSelection(current=>({modality:current.modality,serviceId:current.serviceId,professionalId:current.professionalId}));setIdentifying(false)}if(index===4&&selection.slotId)setIdentifying(true);setSubmission({status:"idle"})}

  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(!selectedSlot)return;
    if(mode!=="live"){setSubmission({status:"error",message:"Este é um horário demonstrativo. A reserva real ainda não está disponível para esta opção."});return}
    const form=new FormData(event.currentTarget);const phone=String(form.get("phone"));const phoneConfirmation=String(form.get("phoneConfirmation"));
    if(phone.replace(/\D/g,"")!==phoneConfirmation.replace(/\D/g,"")){setSubmission({status:"error",message:"Os dois números de WhatsApp precisam ser iguais."});return}
    setSubmission({status:"sending"});
    const response=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slotId:selectedSlot.id,patientName:form.get("patientName"),responsibleName:form.get("responsibleName"),phone,phoneConfirmation,email:form.get("email"),privacyAccepted:form.get("privacyAccepted")==="on"})});
    const payload=await response.json();
    if(response.ok){setSubmission({status:"success",message:`Atendimento confirmado. Enviaremos os detalhes e as próximas orientações para o WhatsApp ${phone}.`});return}
    const fieldMessage=payload.fields?Object.values(payload.fields).flat().find(Boolean):undefined;
    setSubmission({status:"error",message:typeof fieldMessage==="string"?fieldMessage:payload.error??"Não foi possível concluir. Verifique sua conexão e tente novamente."});
  }

  return <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]">
    <section className="rounded-[2rem] border border-[var(--line)] bg-white p-5 shadow-[0_24px_80px_rgba(79,77,78,.06)] sm:p-8">
      <StepNavigation active={activeStep} onSelect={goToStep}/>
      {!selection.modality&&<ChoiceStep title="Como você prefere ser atendido?" description="Escolha a modalidade para ver os atendimentos disponíveis."><ChoiceButton title="Na clínica" detail="Taguatinga Sul · Brasília – DF" onClick={()=>choose("modality","presencial")}/><ChoiceButton title="Online" detail="Atendimento por videochamada" onClick={()=>choose("modality","online")}/></ChoiceStep>}
      {selection.modality&&!selection.serviceId&&<ChoiceStep title="Qual atendimento você procura?" description="A modalidade já foi escolhida; agora selecione o tipo de atendimento.">{availableServices.map(item=><ChoiceButton key={item.id} title={item.name} onClick={()=>choose("serviceId",item.id)}/>)}</ChoiceStep>}
      {selection.serviceId&&!selection.professionalId&&<ChoiceStep title="Com quem você deseja agendar?" description="Escolha um profissional ou encontre o horário mais próximo."><ChoiceButton title="Primeira disponibilidade" detail="Compara os próximos horários entre os profissionais" onClick={()=>choose("professionalId","first-available")} featured/>{availableProfessionals.map(item=><ChoiceButton key={item.id} title={item.name} detail={item.role} onClick={()=>choose("professionalId",item.id)}/>)}</ChoiceStep>}
      {selection.professionalId&&!selection.slotId&&<ChoiceStep title="Escolha o melhor horário" description={mode==="live"?"Compare até três dias de uma vez e avance para as próximas datas.":"Horários demonstrativos para visualizar a experiência."}>{mode==="checking"?<Notice>Consultando a agenda…</Notice>:visibleDays.length?<MultiDayPicker days={visibleDays} index={dayIndex} total={days.length} onPrevious={()=>setDayIndex(value=>Math.max(0,value-3))} onNext={()=>setDayIndex(value=>Math.min(Math.max(days.length-3,0),value+3))} onChoose={id=>choose("slotId",id)} showProfessional={selection.professionalId==="first-available"}/>:<Notice>Não encontramos horários para esta combinação. Escolha outro profissional ou fale com a recepção.</Notice>}</ChoiceStep>}
      {selection.slotId&&selectedSlot&&!identifying&&<div><p className="eyebrow">HORÁRIO SELECIONADO</p><h2 className="mt-4 font-serif text-4xl text-[var(--ink)]">Revise sua escolha.</h2><Summary selection={selection} service={selectedService?.name??""} professional={selectedProfessional?.name??""} slot={selectedSlot}/><div className="mt-5 rounded-2xl border border-[var(--line)] p-4 text-sm leading-6 text-[var(--muted)]"><strong className="text-[var(--ink)]">Pagamento</strong><br/>Nenhum pagamento será solicitado nesta etapa. A opção de pagar antecipadamente ou na clínica será adicionada posteriormente.</div><button className="button button-pink mt-7 w-full sm:w-auto" type="button" onClick={()=>setIdentifying(true)}>Continuar para identificação</button></div>}
      {identifying&&selectedSlot&&submission.status!=="success"&&<IdentificationForm onSubmit={submit} submission={submission}/>}      
      {submission.status==="success"&&selectedSlot&&<div className="mx-auto max-w-2xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[var(--pink-soft)] text-2xl">✓</div><p className="eyebrow mt-6">AGENDAMENTO CONCLUÍDO</p><h2 className="mt-4 font-serif text-4xl text-[var(--ink)]">Seu atendimento foi confirmado.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[var(--muted)]">{submission.message}</p><Summary selection={selection} service={selectedService?.name??""} professional={selectedProfessional?.name??""} slot={selectedSlot}/></div>}
      {selection.modality&&submission.status!=="success"&&<button className="mt-10 text-sm font-semibold text-[var(--muted)] underline decoration-[var(--pink)] underline-offset-4" type="button" onClick={()=>{setSelection({});setIdentifying(false)}}>Recomeçar agendamento</button>}
    </section>
    <aside className="h-fit rounded-[2rem] bg-[var(--blue-soft)] p-7 lg:sticky lg:top-6"><p className="eyebrow">AGENDAMENTO PSIN</p><h2 className="mt-4 font-serif text-3xl text-[var(--ink)]">Escolha com tranquilidade.</h2><p className="mt-4 leading-7 text-[var(--muted)]">Você escolhe a modalidade, o atendimento, o profissional e o horário. Ao finalizar, recebe a confirmação e as orientações pelo WhatsApp informado.</p>{mode==="demo"&&<p className="mt-5 rounded-2xl bg-white/70 p-4 text-sm leading-6 text-[var(--muted)]"><strong className="text-[var(--ink)]">Modo demonstração</strong><br/>Estes horários servem apenas para visualizar o fluxo.</p>}<div className="mt-7 border-t border-[var(--line)] pt-6 text-sm leading-6 text-[var(--muted)]"><strong className="block text-[var(--ink)]">Precisa de ajuda?</strong><p>A recepção pode orientar você sobre modalidades, profissionais e horários.</p><a className="mt-3 inline-block font-semibold text-[var(--ink)] underline decoration-[var(--pink)] underline-offset-4" href="https://wa.me/5561996225522" target="_blank" rel="noreferrer">Conversar pelo WhatsApp</a></div></aside>
  </div>;
}

function StepNavigation({active,onSelect}:{active:number;onSelect:(index:number)=>void}){return <ol className="mb-10 grid grid-cols-5 gap-2" aria-label="Etapas do agendamento">{steps.map((label,index)=><li key={label}><button className={`step-marker w-full text-left ${index<=active?"step-marker-active":""}`} type="button" disabled={index>active} onClick={()=>onSelect(index)}><small>{label}</small></button></li>)}</ol>}
function ChoiceStep({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div><p className="eyebrow">AGENDAMENTO</p><h2 className="mt-4 font-serif text-4xl text-[var(--ink)]">{title}</h2><p className="mt-3 text-[var(--muted)]">{description}</p><div className="mt-8 grid gap-3">{children}</div></div>}
function ChoiceButton({title,detail,onClick,featured=false}:{title:string;detail?:string;onClick:()=>void;featured?:boolean}){return <button className={`choice-card ${featured?"choice-card-featured":""}`} type="button" onClick={onClick}><span><strong>{title}</strong>{detail&&<small>{detail}</small>}</span><span aria-hidden="true">→</span></button>}
function MultiDayPicker({days,index,total,onPrevious,onNext,onChoose,showProfessional}:{days:{date:string;label:string;items:TimeSlot[]}[];index:number;total:number;onPrevious:()=>void;onNext:()=>void;onChoose:(id:string)=>void;showProfessional:boolean}){return <div className="rounded-3xl border border-[var(--line)] p-4 sm:p-5"><div className="mb-5 flex items-center justify-between gap-4"><button className="calendar-arrow" type="button" onClick={onPrevious} disabled={index===0} aria-label="Dias anteriores">←</button><small className="text-center text-[var(--muted)]">{index+1}–{Math.min(index+3,total)} de {total} dias com disponibilidade</small><button className="calendar-arrow" type="button" onClick={onNext} disabled={index+3>=total} aria-label="Próximos dias">→</button></div><div className="grid gap-4 md:grid-cols-3">{days.map(day=><section className="min-w-0 rounded-2xl bg-[var(--surface)] p-4" key={day.date}><h3 className="text-center font-serif text-lg capitalize">{day.label}</h3><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-1">{day.items.map(slot=><button className="rounded-xl border border-[var(--line)] bg-white px-3 py-2.5 text-center transition hover:border-[var(--pink)] hover:bg-[var(--pink-soft)]" key={slot.id} type="button" onClick={()=>onChoose(slot.id)}><strong>{slot.time}</strong>{showProfessional&&<small className="mt-1 block truncate text-[var(--muted)]">{professionals.find(item=>item.id===slot.professionalId)?.name}</small>}</button>)}</div></section>)}</div></div>}
function IdentificationForm({onSubmit,submission}:{onSubmit:(event:FormEvent<HTMLFormElement>)=>void;submission:Submission}){return <form className="mx-auto max-w-3xl" onSubmit={onSubmit}><div className="text-center"><p className="eyebrow">ÚLTIMA ETAPA</p><h2 className="mt-4 font-serif text-4xl text-[var(--ink)]">Dados para confirmação.</h2><p className="mx-auto mt-3 max-w-xl text-[var(--muted)]">Usaremos estes dados somente para confirmar o horário e enviar orientações sobre o atendimento.</p></div><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field name="patientName" label="Nome do paciente" placeholder="Ex.: Maria da Silva" autoComplete="name" required/><Field name="responsibleName" label="Nome do responsável" placeholder="Preencha quando aplicável"/><PhoneField name="phone" label="WhatsApp" placeholder="(61) 99999-9999" autoComplete="tel"/><PhoneField name="phoneConfirmation" label="Confirme o WhatsApp" placeholder="Repita o número" autoComplete="off"/><Field name="email" label="E-mail" type="email" placeholder="Ex.: nome@email.com" autoComplete="email" required wide/></div><label className="mx-auto mt-6 flex max-w-2xl items-start gap-3 text-sm leading-6 text-[var(--muted)]"><input className="mt-1" type="checkbox" name="privacyAccepted" required/><span>Autorizo o uso destes dados para organizar o agendamento e receber sua confirmação.</span></label>{submission.message&&<p className={`mx-auto mt-5 max-w-2xl rounded-2xl p-4 text-sm ${submission.status==="error"?"bg-[#fff0f0] text-[#8d3030]":"bg-[var(--pink-soft)] text-[var(--ink)]"}`} role="alert">{submission.message}</p>}<div className="mt-7 text-center"><button className="button button-pink w-full sm:w-auto" disabled={submission.status==="sending"}>{submission.status==="sending"?"Confirmando…":"Confirmar agendamento"}</button></div></form>}
function PhoneField({name,label,placeholder,autoComplete}:{name:string;label:string;placeholder:string;autoComplete:string}){return <label className="grid gap-2 text-sm font-semibold text-[var(--ink)]"><span>{label} *</span><input className="form-input" name={name} type="tel" required placeholder={placeholder} autoComplete={autoComplete} inputMode="numeric" onInput={event=>{event.currentTarget.value=formatBrazilianPhone(event.currentTarget.value)}}/></label>}
function Field({name,label,type="text",required=false,placeholder,autoComplete,wide=false}:{name:string;label:string;type?:string;required?:boolean;placeholder?:string;autoComplete?:string;wide?:boolean}){return <label className={`grid gap-2 text-sm font-semibold text-[var(--ink)] ${wide?"sm:col-span-2":""}`}><span>{label}{required&&" *"}</span><input className="form-input" name={name} type={type} required={required} placeholder={placeholder} autoComplete={autoComplete}/></label>}
function Summary({selection,service,professional,slot}:{selection:Selection;service:string;professional:string;slot:TimeSlot}){return <dl className="mt-8 grid gap-5 rounded-3xl bg-[var(--surface)] p-6 sm:grid-cols-2"><SummaryItem label="Modalidade" value={selection.modality==="presencial"?"Na clínica":"Online"}/><SummaryItem label="Atendimento" value={service}/><SummaryItem label="Profissional" value={professional}/><SummaryItem label="Data e horário" value={`${slot.dayLabel}, ${slot.time}`}/></dl>}
function SummaryItem({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold tracking-[.14em] text-[var(--muted)] uppercase">{label}</dt><dd className="mt-1 leading-6 text-[var(--ink)]">{value}</dd></div>}
function Notice({children}:{children:React.ReactNode}){return <p className="rounded-2xl bg-[var(--surface)] p-5 text-[var(--muted)]">{children}</p>}
function dateKey(value:string){const date=new Date(value.length===10?`${value}T12:00:00-03:00`:value);return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(date)}
