from pathlib import Path
import re, html, urllib.parse, json
ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'saidas/2026-10-03-reuniao'; SITE=OUT/'site/dist'
wa=lambda name='': 'https://wa.me/5561996225522?text='+urllib.parse.quote('Olá! Gostaria de informações para agendar atendimento'+(' com '+name if name else '')+' na Psin Clínica.')
instagram='https://www.instagram.com/psinclinicapsicologia/'
linktree='https://linktr.ee/psinclinicapsicologia'
def header(prefix=''):
 return f'''<header class="header"><a class="brand" href="{prefix}index.html"><img src="{prefix}logo.jpg" alt="Símbolo da Psin Clínica" width="54" height="54"><span>Psin Clínica</span></a><nav aria-label="Menu principal"><a href="{prefix}index.html#clinica">A clínica</a><a href="{prefix}index.html#equipe">Profissionais</a><a href="{prefix}index.html#ambientes">Ambientes</a><a href="{prefix}index.html#primeiro-contato">Atendimento</a><a href="{prefix}index.html#blog">Blog</a><a class="btn small" href="{wa()}" target="_blank" rel="noopener noreferrer">Agendar</a></nav></header>'''
google='https://www.google.com/maps/search/?api=1&query=Psin+Cl%C3%ADnica+CSE+01+Lote+06+Sala+102+Taguatinga+Sul'
facebook='https://www.facebook.com/psinclinicapsicologia/'
def social_icons():
 icons={
 'Instagram':'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".7"/>',
 'WhatsApp':'<path d="M20 11.5a8 8 0 0 1-12 7L3 20l1.5-5A8 8 0 1 1 20 11.5Z"/><path d="M8 8c0 4 4 7 7 7l1-2-3-1-1 1-2-2 1-1-1-3Z"/>',
 'Google':'<path d="M20 7a9 9 0 1 0 1 8v-3h-9m9 0v3"/>',
 'Facebook':'<path d="M14 21V12h3l.5-4H14V6c0-1 .5-2 2-2h2V1h-3c-4 0-5 2-5 5v2H7v4h3v9"/>'}
 return '<div class="contact-socials">'+''.join(f'<a href="{html.escape(url,quote=True)}" target="_blank" rel="noopener noreferrer" aria-label="{label} da Psin Clínica" title="{label}"><svg viewBox="0 0 24 24" aria-hidden="true">{icons[label]}</svg></a>' for label,url in [('Instagram',instagram),('WhatsApp',wa()),('Google',google),('Facebook',facebook)])+'</div>'
def contact_block():
 return f'''<div class="wrap"><section id="contato" class="contact" aria-labelledby="contact-title"><div><span class="eyebrow">VAMOS CONVERSAR?</span><h2 id="contact-title">O primeiro passo<br>pode ser uma conversa.</h2><a class="btn" href="{wa()}" target="_blank" rel="noopener noreferrer">Fale com a recepção</a></div><div class="contact-details"><p class="contact-location">CSE 01 · Lote 06 · Sala 102<br>Taguatinga Sul · Brasília / DF</p><p>Atendimento presencial e online.</p><a class="text-link" href="tel:+556133514551">(61) 3351-4551</a>{social_icons()}</div></section></div>'''
def page(title,body,prefix=''):
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{html.escape(title)} — Psin Clínica</title><meta name="description" content="Psicologia e psicanálise. Conheça a Psin Clínica, seus profissionais e espaços."><link rel="icon" href="{prefix}logo.jpg"><link rel="stylesheet" href="{prefix}styles.css"></head><body class="{'home' if not prefix else 'inner-page'}"><a class="skip-link" href="#conteudo">Ir para o conteúdo</a><div class="wrap">{header(prefix)}</div><main id="conteudo">{body}</main>{contact_block()}<script src="{prefix}app.js"></script></body></html>'''
people=[
 dict(slug='allice',initials='AG',name='Allice Gracyelli de Melo',role='Psicóloga',reg='CRP 01/15635',approach='Análise do Comportamento Aplicada — ABA',audience='Crianças, famílias e mulheres',bio='Allice é psicóloga e atua com crianças, famílias e mulheres. Seu trabalho inclui a Análise do Comportamento Aplicada e a orientação parental.',color='blue'),
 dict(slug='sandson',initials='SB',name='Sandson Barbosa Azevedo Junior',role='Psicólogo',reg='CRP 01/27483',approach='Terapia Cognitivo-Comportamental — TCC',audience='Públicos e modalidades: consulte a recepção',bio='Sandson é psicólogo formado pela UDF. Sua abordagem de trabalho é a Terapia Cognitivo-Comportamental.',color='pink'),
 dict(slug='emanuele',initials='EM',name='Emanuele Martins Carlos de Souza',role='Psicóloga',reg='CRP DF 29508',approach='Gestalt-terapia',audience='Adolescentes e adultos',bio='Emanuele é psicóloga e atende adolescentes e adultos. Seu trabalho é orientado pela Gestalt-terapia, com atenção à experiência e à história de cada pessoa.',color='blue'),
 dict(slug='suely',initials='SM',name='Suely P. de Melo',role='Psicanalista clínica',reg='Psicanálise',approach='Psicanálise',audience='Mulheres e famílias',bio='Suely é psicanalista clínica, com formação em Letras e Psicanálise. Sua atuação é voltada a mulheres e famílias.',color='pink')]
def portrait(d):return f'<div class="portrait {d["color"]}" aria-hidden="true"><span>{d["initials"]}</span></div>'
def professional(d):
 return f'''<article class="professional">{portrait(d)}<div class="professional-body"><h3>{d['name']}</h3><p class="credential">{d['role']} · {d['reg']}</p><p class="professional-summary">{d['bio']}</p><div class="professional-actions"><a class="btn pink" href="profissionais/{d['slug']}.html">Conheça {d['name'].split()[0]}</a><a class="btn" href="{wa(d['name'])}" target="_blank" rel="noopener noreferrer">Agendar pelo WhatsApp</a></div></div></article>'''
profile_details={
 'allice': 'Formada em Psicologia pela Universidade Paulista (UNIP), Allice também tem formação em Magistério e experiência como professora. Essa trajetória se soma à sua atuação com crianças e famílias. Na clínica, realiza orientação parental e acolhe mulheres em questões como insegurança, ansiedade e sobrecarga emocional.',
 'sandson': 'Sua formação em Psicologia pela UDF é a base de uma trajetória voltada à prática clínica e à Terapia Cognitivo-Comportamental. Em sua apresentação profissional, Sandson dedica atenção à ansiedade e à compreensão das dificuldades emocionais que aparecem no cotidiano.',
 'emanuele': 'Seu trabalho valoriza a experiência no presente, o reconhecimento das emoções e o autoconhecimento. No acompanhamento de adolescentes e adultos, acolhe questões como ansiedade, autoestima, luto e dificuldades emocionais, com atenção à história e ao ritmo de cada pessoa.',
 'suely': 'Sua trajetória reúne a formação em Letras e Psicanálise, a experiência como professora e a atuação como escritora e palestrante. No trabalho clínico com mulheres e famílias, oferece espaço para falar sobre vivências e emoções, com uma escuta atenta à história de cada pessoa.'}
for d in people:
 body=f'''<div class="wrap"><section class="section profile-page"><a class="back-link" href="../index.html#equipe">Voltar aos profissionais</a><div class="profile-layout"><aside class="profile-aside">{portrait(d)}</aside><div class="profile-content"><span class="eyebrow">TRAJETÓRIA E CUIDADO</span><h1>{d['name']}</h1><p class="profile-role">{d['role']} · {d['reg']}</p><p class="profile-approach"><span>Abordagem de trabalho</span><strong>{d['approach']}</strong></p><p class="profile-lead">{d['bio']}</p><p class="profile-description">{profile_details[d['slug']]}</p><div class="profile-note"><h2>O início do acompanhamento</h2><p>O primeiro encontro é um momento para conhecer sua história e conversar sobre o que motivou a busca por cuidado. Os próximos encontros são combinados com o profissional, respeitando as necessidades de cada pessoa.</p><p>A recepção informa as modalidades e os horários disponíveis para atendimento.</p></div><a class="btn pink" href="{wa(d['name'])}" target="_blank" rel="noopener noreferrer">Agendar pelo WhatsApp</a></div></div></section></div>'''
 (SITE/f'profissionais/{d["slug"]}.html').write_text(page(d['name'],body,'../'))
articles=[
 dict(slug='alimentacao-emocoes',cat='ALIMENTAÇÃO E EMOÇÕES',title='Ansiedade e compulsão alimentar: vamos conversar sobre essa relação?',desc='Quando a comida se mistura às emoções, acolher a dificuldade é o começo da conversa.',image='blog-alimentacao.png',refs=[('NIMH · Transtornos alimentares','https://www.nimh.nih.gov/health/publications/eating-disorders'),('NIDDK · Compulsão alimentar','https://www.niddk.nih.gov/health-information/weight-management/binge-eating-disorder/symptoms-causes')],paragraphs=[
 'Você já percebeu que a relação com a comida pode mudar em períodos difíceis? Às vezes essa dúvida aparece sobre nós mesmos; outras vezes, sobre alguém da família. Antes de tirar conclusões, vale olhar para a situação com cuidado e sem transformar a alimentação em motivo de culpa.',
 'Ansiedade e compulsão alimentar podem estar associadas, mas uma não significa automaticamente a presença da outra. Também não existe uma causa única para os transtornos alimentares: aspectos biológicos, emocionais, sociais e do ambiente podem participar desse quadro. Por isso, explicar tudo como “falta de controle” acaba simplificando uma experiência que precisa ser compreendida.',
 'Na compulsão alimentar, podem ocorrer episódios de ingestão de grande quantidade de comida acompanhados da sensação de não conseguir parar. Comer rapidamente, continuar mesmo sem fome e sentir sofrimento depois também podem aparecer. Um episódio isolado ou uma mudança de apetite, porém, não permite estabelecer um diagnóstico.',
 'Se isso acontece com você ou desperta preocupação em relação ao seu filho, a conversa pode começar pelo que a pessoa está vivendo. “Percebi que você não está bem e quero te ouvir” abre um espaço diferente de uma cobrança sobre o prato ou o corpo. Não é necessário encontrar sozinho uma explicação para tudo antes de procurar ajuda.',
 'Quando há episódios recorrentes, perda de controle ou sofrimento com a alimentação, uma avaliação profissional ajuda a entender o que está acontecendo. O cuidado pode envolver acompanhamento psicológico, médico e nutricional, conforme as necessidades da pessoa. A família pode participar como apoio nesse percurso.',
 'É possível pedir ajuda sem ter todas as respostas. O primeiro passo pode ser uma conversa cuidadosa, que leve a dificuldade a sério e acolha quem está passando por ela.']),
 dict(slug='ferias-e-terapia',cat='INFÂNCIA E FAMÍLIA',title='As férias chegaram. E o cuidado com seu filho, como fica?',desc='Entre brincadeiras e mudanças na rotina, o cuidado também encontra espaço nas férias.',image='blog-ferias.png',refs=[('UNICEF · Férias e mudanças na rotina','https://www.unicef.org/parenting/child-care/handling-holidays')],paragraphs=[
 'Alô, mamãe e papai: as férias chegaram e, junto com elas, uma rotina diferente. Tem criança contando os dias para brincar mais, adolescente querendo encontrar os amigos e família tentando equilibrar descanso, trabalho e convivência. Nesse cenário, é natural surgir a pergunta: como fica o acompanhamento psicológico?',
 'O recesso escolar não define, por si só, uma pausa na terapia. A continuidade ou uma interrupção planejada deve ser combinada com o profissional que acompanha a criança ou o adolescente, considerando aquele atendimento. Se haverá viagem ou mudança de horários, essa conversa permite organizar o período e o retorno.',
 'Em casa, as férias não precisam virar uma agenda cheia de atividades. Algumas referências no dia, como refeições, descanso e momentos juntos, podem ajudar a dar previsibilidade sem tirar o espaço da diversão. Um passeio, uma brincadeira ou uma receita em família também podem fazer parte desse tempo.',
 'Há dias em que tudo flui e outros em que aparecem tédio, frustração e conflitos. Isso não precisa transformar cada momento em uma avaliação sobre a evolução do seu filho. Estar junto também inclui escutar, descansar e descobrir o que é possível para a realidade da família.',
 'Se vocês receberam orientações durante o acompanhamento, mantenham como referência aquilo que foi combinado com o profissional. Dúvidas sobre mudanças importantes no período podem ser levadas à equipe pelos canais acordados. A família não precisa assumir o papel de terapeuta nas férias.',
 'Aproveitem o tempo juntos dentro do que couber na vida de vocês. O cuidado não exige férias perfeitas: ele também aparece nos pequenos encontros, nas conversas e nos combinados que ajudam cada pessoa a se sentir considerada.']),
 dict(slug='filmes-emocoes',cat='EMOÇÕES NA INFÂNCIA',title='Depois do filme, a conversa pode continuar.',desc='Uma história na tela pode virar um encontro com o mundo que seu filho está descobrindo.',image='blog-filmes.png',refs=[('UNICEF · Conversas sobre emoções','https://www.unicef.org/sop/positive-parenting')],paragraphs=[
 'O filme acaba, os créditos sobem e seu filho ainda está falando de uma cena. Talvez tenha achado uma parte engraçada, ficado com medo de um personagem ou se incomodado com o final. Esse comentário espontâneo pode ser uma oportunidade de conversar, sem transformar a sessão em uma aula.',
 'Histórias de filmes e livros oferecem situações que podem ajudar a falar sobre sentimentos. Em vez de começar com uma explicação pronta, você pode perguntar o que chamou a atenção da criança. “Como você acha que aquele personagem se sentiu?” é um convite para conhecer a leitura dela sobre a história.',
 'A resposta pode surpreender. A cena que pareceu triste para um adulto talvez tenha despertado raiva, curiosidade ou nenhuma emoção especial na criança. Não é preciso encontrar uma resposta correta. O valor desse momento está também em escutar uma perspectiva diferente da sua.',
 'Se a conversa abrir esse espaço, vocês podem lembrar de situações do cotidiano. Uma despedida, uma amizade ou uma frustração na escola talvez apareça no caminho. Mas a criança também pode preferir voltar a brincar, e tudo bem deixar a conversa para outra oportunidade.',
 'A proposta é estar disponível para ouvir, com palavras que façam sentido para a idade e para aquela família. Uma fala depois do filme não é um teste nem permite concluir o que a criança está sentindo em todas as outras situações.',
 'Na próxima sessão em família, escolha uma história adequada à idade e reserve um pouco de tempo para estar junto. Às vezes, a conversa começa com uma pergunta pequena. Em outras, ela aparece mais tarde, quando ninguém estava esperando.'])]
def blog_card(a,compact=False,prefix=''):
 return f'''<article class="blog-card {'compact' if compact else 'featured'}"><a class="blog-photo" href="{prefix}blog/{a['slug']}.html"><img src="{prefix}images/{a['image']}" alt="Imagem ilustrativa sobre {a['cat'].lower()}" loading="lazy"></a><div class="blog-card-body"><span class="eyebrow">{a['cat']}</span><h3><a href="{prefix}blog/{a['slug']}.html">{a['title']}</a></h3>{'' if compact else '<p>'+a['desc']+'</p>'}<a class="read-link" href="{prefix}blog/{a['slug']}.html">Ler artigo</a></div></article>'''
for a in articles:
 body=f'''<div class="wrap"><article class="article-page"><a class="back-link" href="index.html">Voltar ao blog</a><header class="article-heading"><span class="eyebrow">{a['cat']}</span><h1>{a['title']}</h1><p>{a['desc']}</p></header><figure class="article-cover"><img src="../images/{a['image']}" alt="Imagem ilustrativa sobre {a['cat'].lower()}"><figcaption>Imagem ilustrativa gerada por IA.</figcaption></figure><div class="article-body">{''.join('<p>'+t+'</p>' for t in a['paragraphs'])}<div class="article-sources">Referências: {', '.join('<a href="'+url+'" target="_blank" rel="noopener noreferrer">'+label+'</a>' for label,url in a['refs'])}.</div><p class="article-disclaimer">Conteúdo educativo. Uma orientação individual depende da avaliação de um profissional.</p><div class="article-cta"><h2>Vamos conversar?</h2><a class="btn" href="{wa()}" target="_blank" rel="noopener noreferrer">Fale com a Psin</a></div></div></article></div>'''
 (SITE/f'blog/{a["slug"]}.html').write_text(page(a['title'],body,'../'))
listing='<div class="wrap"><section class="section"><span class="eyebrow">BLOG DA PSIN</span><h1>Conversas que<br>continuam em casa.</h1><p class="lead">Infância, emoções e convivência, com espaço para as dúvidas de quem cuida.</p><div class="blog-list">'+''.join(blog_card(a,prefix='../') for a in articles)+'</div></section></div>'
(SITE/'blog/index.html').write_text(page('Blog',listing,'../'))
for old in ['rotina-familia.html','brincar-juntos.html']:
 f=SITE/'blog'/old
 if f.exists():f.unlink()
blog='<section id="blog" class="section"><div class="section-heading"><div><span class="pill">CONVERSAS COM A FAMÍLIA</span><h2>Blog da Psin.</h2></div></div><div class="blog-layout">'+blog_card(articles[0])+'<div class="blog-side">'+''.join(blog_card(a,True) for a in articles[1:])+'</div></div><div class="section-action"><a class="btn pink" href="blog/index.html">Ver todos os artigos</a></div></section>'
hero=f'''<section class="hero"><figure class="hero-picture"><img src="images/hero-parede-direita.png" alt="Apresentação da marca Psin Clínica no espaço da clínica" fetchpriority="high"></figure><div class="wrap hero-inner"><div class="hero-copy"><span class="eyebrow"><span class="dot"></span>PSICOLOGIA E PSICANÁLISE</span><h1>Um espaço<br>para escutar.<br><em>Um primeiro passo<br>para conversar.</em></h1><p class="lead">Sua história merece tempo, atenção e escuta.</p><div class="actions"><a class="btn" href="{wa()}" target="_blank" rel="noopener noreferrer">Fale com a recepção</a><a class="btn pink" href="#clinica">Conheça a clínica</a></div></div></div></section>'''
about='''<section id="clinica" class="section clinic-intro"><div class="clinic-heading"><span class="pill">A CLÍNICA</span><h2>Cuidado para cada fase.<br>Espaço para cada história.</h2><a class="btn pink" href="#equipe">Conheça nossos profissionais</a></div><div class="clinic-prose"><p>A Psin Clínica é um espaço de psicologia e psicanálise para crianças, adolescentes e adultos. Aqui, diferentes histórias encontram lugar para ser ouvidas, com atenção ao momento de vida de cada pessoa.</p><p>Na infância, esse cuidado também conversa com quem está por perto. A participação dos responsáveis faz parte dos combinados construídos com o profissional, respeitando as necessidades de cada atendimento.</p><p>Nossos profissionais têm percursos e abordagens próprios. Conhecer quem vai acompanhar você ou sua família é parte desse encontro.</p></div></section>'''
team='<section id="equipe" class="section"><div class="section-heading"><div><span class="pill">PROFISSIONAIS</span><h2>Uma equipe para<br>cuidar de você.</h2></div></div><div class="professionals">'+''.join(professional(d) for d in people)+'</div></section>'
gallery='''<section id="ambientes" class="section"><div class="section-heading"><div><span class="pill">NOSSOS AMBIENTES</span><h2>Conheça nossos ambientes.</h2></div></div><div class="environment-grid"><img src="images/recepcao-clinica.png" alt="Recepção da clínica com cadeiras e balcão" loading="lazy"><img src="images/sala-clinica.png" alt="Sala de atendimento com duas poltronas" loading="lazy"><img src="images/psin-clinica.png" alt="Apresentação da marca no espaço da Psin" loading="lazy"></div></section>'''
process='''<section id="primeiro-contato" class="process-section"><div class="wrap"><div class="center-heading"><span class="pill">COMO FUNCIONA O ATENDIMENTO</span><h2>O cuidado se constrói<br>ao longo dos encontros.</h2><p>Da chegada à continuidade, cada etapa abre espaço para conhecer sua história.</p></div><ol class="process-steps"><li tabindex="0"><span>01</span><h3>Acolhimento</h3><p>A recepção organiza o primeiro contato, apresenta as opções de atendimento e combina o encontro com o profissional.</p></li><li tabindex="0"><span>02</span><h3>Primeiros encontros</h3><p>Os primeiros encontros são dedicados à escuta da história e à compreensão do que motivou a busca por acompanhamento.</p></li><li tabindex="0"><span>03</span><h3>Cuidado em conjunto</h3><p>O profissional apresenta sua forma de trabalhar e constrói os combinados do atendimento. Na infância, a participação dos responsáveis também é alinhada.</p></li><li tabindex="0"><span>04</span><h3>Acompanhamento</h3><p>O acompanhamento se desenvolve conforme as necessidades da pessoa. A frequência e os próximos passos são definidos ao longo desse processo.</p></li></ol></div></section>'''
faq='''<section id="duvidas" class="section faq-grid"><div><span class="pill">DÚVIDAS FREQUENTES</span><h2>Antes do<br>primeiro encontro.</h2><p>Algumas respostas para começar com mais clareza.</p></div><div class="faq-items"><details><summary>Como posso solicitar atendimento?</summary><p>Fale com a recepção pelo WhatsApp para consultar profissionais e horários. O atendimento é agendado após a confirmação da clínica.</p></details><details><summary>Existe atendimento online?</summary><p>Sim. A modalidade disponível depende do profissional e do atendimento solicitado. A recepção orienta sobre as opções e o acesso ao encontro online.</p></details><details><summary>Como conheço os profissionais?</summary><p>Na seção de profissionais, você encontra uma apresentação individual, abordagem e público atendido. Cada perfil tem um botão para solicitar agendamento.</p></details><details><summary>Quais são os valores e formas de pagamento?</summary><p>A recepção informa os valores e as condições conforme o atendimento escolhido, além das regras de remarcação e cancelamento.</p></details><details><summary>Os responsáveis participam do atendimento infantil?</summary><p>A participação dos responsáveis é combinada com o profissional, considerando a criança e o momento do acompanhamento. A organização do primeiro encontro é confirmada antes da consulta.</p></details></div></section>'''
reviews='''<section id="avaliacoes" class="section reviews-section"><div class="section-heading"><div><span class="pill">AVALIAÇÕES</span><h2>O acolhimento<br>também fica nas palavras.</h2></div><p class="reviews-demo">Demonstração visual · relatos fictícios</p></div><div class="review-grid"><article class="review"><span class="review-quote" aria-hidden="true">“</span><p>Desde o primeiro contato, recebemos as informações com clareza. Foi bom chegar sabendo como seria o encontro.</p><div class="review-person"><span>01</span><div><strong>Exemplo de avaliação</strong><small>Texto fictício para demonstração</small></div></div></article><article class="review"><span class="review-quote" aria-hidden="true">“</span><p>Encontramos um ambiente tranquilo e espaço para apresentar nossas dúvidas com calma.</p><div class="review-person"><span>02</span><div><strong>Exemplo de avaliação</strong><small>Texto fictício para demonstração</small></div></div></article><article class="review"><span class="review-quote" aria-hidden="true">“</span><p>A atenção no atendimento e a forma de explicar os próximos passos fizeram diferença na nossa chegada.</p><div class="review-person"><span>03</span><div><strong>Exemplo de avaliação</strong><small>Texto fictício para demonstração</small></div></div></article></div></section>'''
reviews=reviews.replace('</section>', '<div class="review-invitation"><div><h3>Sua experiência também importa.</h3><p>Já conhece a Psin? Compartilhe sua avaliação no perfil da clínica no Google.</p></div><a class="btn pink" href="https://www.google.com/maps/search/?api=1&amp;query=Psin+Cl%C3%ADnica+CSE+01+Lote+06+Sala+102+Taguatinga+Sul" target="_blank" rel="noopener noreferrer">Encontre a Psin no Google</a></div></section>')

body=hero+'<div class="wrap"><div class="strip"><div><span>Onde estamos</span><strong>Taguatinga Sul · Brasília / DF</strong></div><div><span>Como atendemos</span><strong>Presencial e online</strong></div><div><span>Para quem cuidamos</span><strong>Crianças, adolescentes e adultos</strong></div></div>'+about+team+gallery+'</div>'+process+'<div class="wrap">'+faq+reviews+blog+'</div>'
(SITE/'index.html').write_text(page('Psicologia e psicanálise',body))
(OUT/'REVISAO-EDITORIAL.md').write_text('''# Revisão editorial antes da publicação

A interface foi preparada para apresentação final, sem avisos de protótipo. O site continua local, com noindex e sem publicação externa.

- Confirmar equipe ativa, registros, públicos, biografias e abordagens com cada profissional. Não foram criadas formações ou especialidades adicionais. Sandson: público ainda depende de confirmação.
- Aprovar texto institucional e descrição do processo com a responsável técnica.
- Revisar artigos de alimentação e emoções, férias e filmes. Fontes estão nas páginas. Não há orientação para interromper terapia automaticamente nas férias.
- Os três relatos da área de avaliações são fictícios, explicitamente marcados na interface. Substituir por relatos reais autorizados e aprovados antes da publicação.
- Confirmar o link direto de avaliação do Google; a chamada atual abre a busca da clínica no Maps, sem simular um formulário de avaliação.
- Confirmar telefone, endereço e perfis sociais. Facebook extraído dos documentos de pesquisa fornecidos: https://www.facebook.com/psinclinicapsicologia/. WhatsApp abre mensagem preenchida e depende do envio pelo visitante.
- Incluir retratos reais autorizados da equipe; até lá, os cartões usam iniciais.
- As fotografias da clínica foram aprimoradas por IA. A hero foi recomposta para ampliar a parede à esquerda e posicionar marca e objetos à direita; trata-se de adaptação visual. Conferir fidelidade dos detalhes.
- As capas do blog são imagens editoriais geradas por IA e não representam pacientes.
''')
