import { NextResponse } from "next/server";
import { z } from "zod";
import { requireStaff } from "@/lib/auth/require-staff";
import { formatBrazilianPhone } from "@/lib/phone";
const schema=z.object({professionalId:z.string().uuid().optional(),serviceId:z.string().uuid(),modality:z.enum(["presencial","online"]),patientName:z.string().trim().min(3).max(120),responsibleName:z.string().trim().max(120).optional(),phone:z.string().trim().min(10).max(20),email:z.string().email(),startsOn:z.iso.date(),endsOn:z.iso.date(),startTime:z.string().regex(/^\d{2}:\d{2}$/),intervalDays:z.number().int().min(1).max(365),durationMinutes:z.number().int().min(20).max(240)});
export async function POST(request:Request){const auth=await requireStaff(request);if("error" in auth)return NextResponse.json({error:auth.error},{status:auth.status});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Confira todos os campos do acompanhamento.",details:process.env.NODE_ENV==="development"?parsed.error.flatten().fieldErrors:undefined},{status:400});const professionalId=auth.staff.role==="professional"?auth.staff.professional_id:parsed.data.professionalId;if(!professionalId)return NextResponse.json({error:"Profissional não identificado."},{status:400});const d=parsed.data;const {data,error}=await auth.supabase.rpc("create_recurring_appointment",{p_professional_id:professionalId,p_service_id:d.serviceId,p_modality:d.modality,p_patient_name:d.patientName,p_responsible_name:d.responsibleName??"",p_phone:formatBrazilianPhone(d.phone),p_email:d.email,p_starts_on:d.startsOn,p_ends_on:d.endsOn,p_local_start_time:d.startTime,p_interval_days:d.intervalDays,p_duration_minutes:d.durationMinutes,p_created_by:auth.user.id});if(error){console.error("Recurring appointment error",error);const match=error.message.match(/recurrence_conflict_on_(\d{4})-(\d{2})-(\d{2})/);const conflict=Boolean(match)||error.message.includes("conflict");const conflictDate=match?`${match[3]}/${match[2]}/${match[1]}`:"uma das datas escolhidas";return NextResponse.json({error:conflict?`O horário já está ocupado em ${conflictDate}. Escolha outro horário ou ajuste o período.`:"Não foi possível criar o acompanhamento.",details:process.env.NODE_ENV==="development"?error.message:undefined},{status:conflict?409:500})}return NextResponse.json({id:data},{status:201})}

const updateSchema=schema.omit({patientName:true,responsibleName:true,phone:true,email:true,professionalId:true}).extend({id:z.string().uuid()});
export async function PATCH(request:Request){const auth=await requireStaff(request);if("error" in auth)return NextResponse.json({error:auth.error},{status:auth.status});const parsed=updateSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Confira os dados do acompanhamento."},{status:400});const recurrence=await auth.supabase.from("recurring_appointments").select("professional_id").eq("id",parsed.data.id).maybeSingle();if(recurrence.error||!recurrence.data)return NextResponse.json({error:"Acompanhamento não encontrado."},{status:404});if(auth.staff.role==="professional"&&recurrence.data.professional_id!==auth.staff.professional_id)return NextResponse.json({error:"Acesso não autorizado."},{status:403});const d=parsed.data;const {error}=await auth.supabase.rpc("update_recurring_appointment",{p_recurrence_id:d.id,p_service_id:d.serviceId,p_modality:d.modality,p_starts_on:d.startsOn,p_ends_on:d.endsOn,p_local_start_time:d.startTime,p_interval_days:d.intervalDays,p_duration_minutes:d.durationMinutes});if(error){const match=error.message.match(/recurrence_conflict_on_(\d{4})-(\d{2})-(\d{2})/);return NextResponse.json({error:match?`O novo horário está ocupado em ${match[3]}/${match[2]}/${match[1]}.`:"Não foi possível atualizar o acompanhamento. Execute a migração 006 caso ela ainda esteja pendente."},{status:match?409:500})}return NextResponse.json({ok:true})}
