import Image from "next/image";
import Link from "next/link";

const whatsapp="https://wa.me/5561996225522?text=Ol%C3%A1%21%20Gostaria%20de%20informa%C3%A7%C3%B5es%20sobre%20atendimento%20na%20Psin%20Cl%C3%ADnica.";

export function SiteHeader(){return <><a className="skip-link" href="#conteudo">Ir para o conteúdo</a><div className="wrap"><header className="header"><Link className="brand" href="/"><Image src="/institutional/logo.jpg" alt="Símbolo da Psin Clínica" width={54} height={54}/><span>Psin Clínica</span></Link><nav aria-label="Menu principal"><Link href="/#clinica">A clínica</Link><Link href="/#equipe">Profissionais</Link><Link href="/#ambientes">Ambientes</Link><Link href="/#primeiro-contato">Atendimento</Link><Link href="/#blog">Blog</Link><Link className="btn small" href="/agendamento">Agendar</Link></nav></header></div></>}

function SocialIcon({children}:{children:React.ReactNode}){return <span aria-hidden="true" style={{fontSize:12,fontWeight:700}}>{children}</span>}
export function SiteFooter(){return <><div className="wrap"><section id="contato" className="contact" aria-labelledby="contact-title"><div className="contact-intro"><div><span className="eyebrow">VAMOS CONVERSAR?</span><h2 id="contact-title">O primeiro passo<br/>pode ser uma conversa.</h2></div><p className="contact-location">Atendimento presencial e online.</p><a className="btn" href={whatsapp} target="_blank" rel="noopener noreferrer">Fale com a recepção</a><div className="contact-channels"><h3>Contatos</h3><a className="contact-phone" href="tel:+556133514551">(61) 3351-4551</a><div className="contact-socials"><a href="https://www.instagram.com/psinclinicapsicologia/" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon>IG</SocialIcon></a><a href={whatsapp} target="_blank" rel="noreferrer" aria-label="WhatsApp"><SocialIcon>WA</SocialIcon></a><a href="https://www.google.com/maps/search/?api=1&query=Psin+Cl%C3%ADnica+CSE+01+Lote+06+Sala+102+Taguatinga+Sul" target="_blank" rel="noreferrer" aria-label="Google"><SocialIcon>G</SocialIcon></a><a href="https://www.facebook.com/psinclinicapsicologia/" target="_blank" rel="noreferrer" aria-label="Facebook"><SocialIcon>f</SocialIcon></a></div></div></div><div className="contact-map"><h3>Endereço</h3><address className="contact-address"><span>CSE 01 · Lote 06 · Sala 102</span><span>Taguatinga Sul · Brasília – DF</span><span>CEP 72025-015</span></address><iframe title="Mapa da Psin Clínica" src="https://www.google.com/maps?q=Psin+Clinica+CSE+01+Lote+06+Sala+102+Taguatinga+Sul+Brasilia+DF&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Psin+Cl%C3%ADnica+CSE+01+Lote+06+Sala+102+Taguatinga+Sul" target="_blank" rel="noreferrer">Abrir no Google Maps</a></div><nav className="contact-nav" aria-label="Navegação ao final"><h3>Navegação</h3><Link href="/#clinica">A clínica</Link><Link href="/#equipe">Profissionais</Link><Link href="/#ambientes">Ambientes</Link><Link href="/#primeiro-contato">Atendimento</Link><Link href="/#duvidas">Dúvidas</Link><Link href="/#blog">Blog</Link><span className="contact-nav-divider"/><Link href="/profissional">Área profissional</Link><Link href="/recepcao">Área da recepção</Link></nav></section></div><a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Conversar pelo WhatsApp"><svg className="brand-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.6a8 8 0 0 1-11.8 7L4 20l1.4-4A8 8 0 1 1 20 11.6Z"/><path d="M9 8.5c.3 2.8 2 4.5 4.8 5l1-1.1 1.7.8-.3 1.6c-4.6.8-8-2.7-7.9-7.2L9 7Z"/></svg><span>Converse pelo WhatsApp</span></a></>}
