import { NextResponse } from "next/server";
import { z } from "zod";
import { requireStaff } from "@/lib/auth/require-staff";

const ruleSchema=z.object({professionalId:z.string().uuid().optional(),weekday:z.number().int().min(0).max(6),startsAt:z.string().regex(/^\d{2}:\d{2}$/),endsAt:z.string().regex(/^\d{2}:\d{2}$/),modality:z.enum(["presencial","online"])});
function permittedProfessional(staff:{role:string;professional_id:string|null},requested:string|null){if(staff.role==="professional")return staff.professional_id;if(staff.role==="admin")return requested;return null}

export async function GET(request:Request){const auth=await requireStaff(request);if("error" in auth)return NextResponse.json({error:auth.error},{status:auth.status});const url=new URL(request.url);const professionalId=permittedProfessional(auth.staff,url.searchParams.get("professionalId"));if(!professionalId)return NextResponse.json({error:"Selecione ou vincule um profissional."},{status:400});const [rules,exceptions,recurrences,appointments,services,professionals]=await Promise.all([auth.supabase.from("availability_rules").select("*").eq("professional_id",professionalId).eq("active",true).order("weekday").order("starts_at"),auth.supabase.from("schedule_exceptions").select("*").eq("professional_id",professionalId).gte("ends_at",new Date().toISOString()).order("starts_at"),auth.supabase.from("recurring_appointments").select("id,service_id,modality,patient_name,responsible_name,phone,email,starts_on,ends_on,local_start_time,interval_days,duration_minutes,active,services(name)").eq("professional_id",professionalId).eq("active",true).order("local_start_time"),auth.supabase.from("appointments").select("id,patient_name,responsible_name,phone,email,starts_at,ends_at,status,modality,recurring_appointment_id,services(name)").eq("professional_id",professionalId).in("status",["pending","confirmed"]).gte("starts_at",new Date().toISOString()).order("starts_at").limit(300),auth.supabase.from("services").select("id,name,duration_minutes,buffer_minutes").eq("active",true),auth.supabase.from("professionals").select("id,name").eq("active",true).order("name")]);const failure=[rules,exceptions,recurrences,appointments,services,professionals].find(r=>r.error);if(failure?.error)return NextResponse.json({error:"Não foi possível carregar a agenda profissional."},{status:500});const legacyOnline=new Set(["teleconsulta","psicoterapia online"]);return NextResponse.json({staff:auth.staff,professionalId,rules:rules.data,exceptions:exceptions.data,recurrences:recurrences.data,appointments:appointments.data,services:services.data?.filter(service=>!legacyOnline.has(service.name.toLocaleLowerCase("pt-BR"))),professionals:professionals.data})}

export async function POST(request:Request){const auth=await requireStaff(request);if("error" in auth)return NextResponse.json({error:auth.error},{status:auth.status});const parsed=ruleSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Revise o intervalo informado."},{status:400});const professionalId=permittedProfessional(auth.staff,parsed.data.professionalId??null);if(!professionalId)return NextResponse.json({error:"Profissional sem autorização."},{status:403});const {data,error}=await auth.supabase.from("availability_rules").insert({professional_id:professionalId,weekday:parsed.data.weekday,starts_at:parsed.data.startsAt,ends_at:parsed.data.endsAt,modality:parsed.data.modality}).select().single();if(error)return NextResponse.json({error:error.code==="23505"?"Esse intervalo já existe.":"Não foi possível salvar o intervalo."},{status:error.code==="23505"?409:500});return NextResponse.json(data,{status:201})}

export async function DELETE(request:Request){const auth=await requireStaff(request);if("error" in auth)return NextResponse.json({error:auth.error},{status:auth.status});const id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Intervalo não informado."},{status:400});const query=auth.supabase.from("availability_rules").update({active:false}).eq("id",id);if(auth.staff.role==="professional")query.eq("professional_id",auth.staff.professional_id);const {error}=await query;if(error)return NextResponse.json({error:"Não foi possível remover o intervalo."},{status:500});return NextResponse.json({ok:true})}
